# Generated by Django 5.0.6 on 2026-04-30 05:21

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Page title tag. 50–60 chars ideal. Leave blank to auto-derive.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description. 120–155 chars ideal. Leave blank to auto-derive.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing previews. 1200×630px recommended.', null=True, upload_to='og_images/%Y/%m/')),
                ('og_image_alt', models.CharField(blank=True, help_text='Alt text for the OG image — used by screen readers and some social platforms.', max_length=200)),
                ('name', models.CharField(help_text="e.g. 'British Columbia', 'Nevada', 'Peru'", max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('country', models.CharField(help_text="Parent country, e.g. 'Canada'. For country-level rows, repeat the name here.", max_length=80)),
                ('country_code', models.CharField(blank=True, help_text="ISO 3166-1 alpha-2, e.g. 'CA', 'US', 'AU'.", max_length=2)),
                ('region_type', models.CharField(choices=[('country', 'Country'), ('province', 'Province'), ('state', 'State'), ('territory', 'Territory'), ('region', 'Region')], default='country', max_length=12)),
                ('permitting_score', models.PositiveSmallIntegerField(help_text='Permitting timeline & predictability. 1 = years of delay / unpredictable. 5 = clear, fast, predictable.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('permitting_notes', models.TextField(blank=True, help_text='One-sentence justification.')),
                ('fiscal_score', models.PositiveSmallIntegerField(help_text='Fiscal regime stability — royalties, tax, no surprise changes. 1 = recent hostile changes. 5 = stable for decades.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fiscal_notes', models.TextField(blank=True)),
                ('political_score', models.PositiveSmallIntegerField(help_text='Political & security risk. 1 = active conflict / expropriation risk. 5 = stable democracy, rule of law.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('political_notes', models.TextField(blank=True)),
                ('infrastructure_score', models.PositiveSmallIntegerField(help_text='Infrastructure & power. 1 = remote, no roads/grid. 5 = full road, rail, power access.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('infrastructure_notes', models.TextField(blank=True)),
                ('community_score', models.PositiveSmallIntegerField(help_text='Indigenous, community, ESG complexity. 1 = blocked / litigation. 5 = strong community support, clear consultation framework.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('community_notes', models.TextField(blank=True)),
                ('summary', models.TextField(help_text='2–4 paragraph plain-language summary of why this jurisdiction earned its scores.')),
                ('whats_changed', models.TextField(blank=True, help_text="Optional 'what changed recently' note — new legislation, election outcomes, recent permits granted/denied.")),
                ('last_assessed_at', models.DateField(blank=True, help_text='Date this assessment was last reviewed. Update annually after Fraser Institute releases.', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='jurisdiction',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='uniq_country_name'),
        ),
    ]
