# Generated by Django 5.0.6 on 2026-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credentials',
            field=models.TextField(blank=True, help_text='Professional background, qualifications, years of experience. Displayed on author profile page.'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_title',
            field=models.CharField(blank=True, help_text="E.g. 'Independent Mining Stock Analyst'. Used in Person schema.", max_length=100),
        ),
    ]
