# Generated by Django 5.0.6 on 2026-04-10 21:10

import autoslug.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Page title tag. 50–60 chars ideal. Leave blank to auto-derive.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description. 120–155 chars ideal. Leave blank to auto-derive.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing previews. 1200×630px recommended.', null=True, upload_to='og_images/%Y/%m/')),
                ('og_image_alt', models.CharField(blank=True, help_text='Alt text for the OG image — used by screen readers and some social platforms.', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('ticker', models.CharField(max_length=10)),
                ('exchange', models.CharField(choices=[('TSXV', 'TSX Venture (TSXV)'), ('TSX', 'Toronto Stock Exchange (TSX)'), ('ASX', 'Australian Securities Exchange (ASX)'), ('OTC', 'OTC Markets'), ('NYSE', 'NYSE / NYSE American'), ('LSE', 'London Stock Exchange (LSE)'), ('OTHER', 'Other')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('market_cap_cad', models.BigIntegerField(blank=True, help_text='Market cap in CAD cents to avoid float issues.', null=True)),
                ('jurisdiction', models.CharField(blank=True, help_text='e.g. British Columbia, Nevada, Peru', max_length=100)),
                ('primary_commodity', models.CharField(blank=True, help_text='e.g. Gold, Copper, Silver', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VerdictScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Page title tag. 50–60 chars ideal. Leave blank to auto-derive.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description. 120–155 chars ideal. Leave blank to auto-derive.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing previews. 1200×630px recommended.', null=True, upload_to='og_images/%Y/%m/')),
                ('og_image_alt', models.CharField(blank=True, help_text='Alt text for the OG image — used by screen readers and some social platforms.', max_length=200)),
                ('management_score', models.PositiveSmallIntegerField(help_text='1 = No insider ownership / red flags. 5 = Significant aligned ownership.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('management_notes', models.TextField(blank=True)),
                ('geology_score', models.PositiveSmallIntegerField(help_text='1 = Inferred only / poor grade. 5 = Measured+Indicated with strong grade/scale.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('geology_notes', models.TextField(blank=True)),
                ('capital_score', models.PositiveSmallIntegerField(help_text='1 = Highly diluted / warrant overhang. 5 = Clean structure, funded.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('capital_notes', models.TextField(blank=True)),
                ('catalyst_score', models.PositiveSmallIntegerField(help_text='1 = No near-term catalysts. 5 = Drill results / feasibility imminent.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('catalyst_notes', models.TextField(blank=True)),
                ('acquisition_score', models.PositiveSmallIntegerField(help_text='1 = Trading at/above peer acquisition multiples. 5 = Deep discount to peers.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('acquisition_notes', models.TextField(blank=True)),
                ('verdict', models.CharField(choices=[('BUY', 'Buy'), ('WATCH', 'Watch'), ('AVOID', 'Avoid')], max_length=5)),
                ('analyst_summary', models.TextField(help_text='Plain-language summary published with the scorecard.')),
                ('nav_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('p_nav_multiple', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('scored_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='verdict.company')),
            ],
            options={
                'ordering': ['-scored_at'],
            },
        ),
    ]
