# Generated by Django 5.0.6 on 2026-04-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdict', '0004_regenerate_company_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tier',
            field=models.CharField(choices=[('junior', 'Junior / Explorer'), ('mid', 'Mid-Tier Producer'), ('major', 'Major Producer')], default='junior', help_text='Controls page layout. Juniors show Verdict Framework. Majors/mid-tiers show producer profile.', max_length=10),
        ),
    ]
