# Generated by Django 5.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdict', '0015_shellcandidate_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('warrant', 'Warrant'), ('option', 'Option')], max_length=10)),
                ('count', models.PositiveBigIntegerField(help_text='Number of warrants or options in this tranche.')),
                ('strike_price', models.DecimalField(blank=True, decimal_places=4, help_text="Strike price (in the company's listing currency). Leave blank if unknown.", max_digits=10, null=True)),
                ('expiry', models.DateField(blank=True, help_text='Expiry date. Leave blank if unknown.', null=True)),
                ('notes', models.CharField(blank=True, help_text="Optional label, e.g. 'Tranche A', 'Director options', 'Broker warrants'.", max_length=120)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_instruments', to='verdict.verdictscorecard')),
            ],
            options={
                'ordering': ['type', 'strike_price', 'expiry'],
            },
        ),
        migrations.AddField(
            model_name='verdictscorecard',
            name='resource_measured',
            field=models.CharField(blank=True, help_text="Measured resource (e.g. '1.2 Moz Au @ 1.5 g/t').", max_length=120),
        ),
        migrations.AddField(
            model_name='verdictscorecard',
            name='resource_indicated',
            field=models.CharField(blank=True, help_text='Indicated resource.', max_length=120),
        ),
        migrations.AddField(
            model_name='verdictscorecard',
            name='resource_inferred',
            field=models.CharField(blank=True, help_text='Inferred resource.', max_length=120),
        ),
        migrations.AddField(
            model_name='verdictscorecard',
            name='reserve_proven',
            field=models.CharField(blank=True, help_text='Proven reserve.', max_length=120),
        ),
        migrations.AddField(
            model_name='verdictscorecard',
            name='reserve_probable',
            field=models.CharField(blank=True, help_text='Probable reserve.', max_length=120),
        ),
        migrations.AddField(
            model_name='verdictscorecard',
            name='shares_issued_outstanding',
            field=models.PositiveBigIntegerField(blank=True, help_text='Issued and outstanding share count.', null=True),
        ),
        migrations.AddField(
            model_name='verdictscorecard',
            name='shares_fully_diluted',
            field=models.PositiveBigIntegerField(blank=True, help_text='Fully diluted share count (includes warrants + options).', null=True),
        ),
    ]
