# Generated by Django 5.0.6 on 2026-04-30 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdictions', '0001_initial'),
        ('verdict', '0016_shareinstrument_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyqueue',
            new_name='verdict_com_status_1a5e2a_idx',
            old_name='verdict_com_status_cb3f39_idx',
        ),
        migrations.RenameIndex(
            model_name='shellcandidate',
            new_name='verdict_she_status_bf4020_idx',
            old_name='verdict_she_status_8f50a8_idx',
        ),
        migrations.AddField(
            model_name='company',
            name='primary_jurisdiction',
            field=models.ForeignKey(blank=True, help_text='Primary operating jurisdiction. Pulls the risk score onto the company page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='jurisdictions.jurisdiction'),
        ),
        migrations.AlterField(
            model_name='company',
            name='jurisdiction',
            field=models.CharField(blank=True, help_text='Free-text jurisdiction (legacy; agent-filled). Prefer setting primary_jurisdiction FK below.', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending verification'), ('active', 'Active — ready to promote'), ('promoted', 'Promoted to Company'), ('delisted', 'Delisted'), ('acquired', 'Acquired'), ('out_of_scope', 'Out of scope (exchange)'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
