# Generated by Django 5.0.6 on 2026-05-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdict', '0017_rename_verdict_com_status_cb3f39_idx_verdict_com_status_1a5e2a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareinstrument',
            options={'ordering': ['type', 'strike_price', 'issue_price', 'expiry', 'hold_release_date']},
        ),
        migrations.AddField(
            model_name='shareinstrument',
            name='hold_release_date',
            field=models.DateField(blank=True, help_text='Date the 4-month flow-through hold expires and shares free-trade.', null=True),
        ),
        migrations.AddField(
            model_name='shareinstrument',
            name='issue_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Issue price (flow-through tranches). The headline placement price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shareinstrument',
            name='count',
            field=models.PositiveBigIntegerField(help_text='Number of warrants, options, or flow-through shares in this tranche.'),
        ),
        migrations.AlterField(
            model_name='shareinstrument',
            name='expiry',
            field=models.DateField(blank=True, help_text='Expiry date (warrants/options). Leave blank if unknown.', null=True),
        ),
        migrations.AlterField(
            model_name='shareinstrument',
            name='notes',
            field=models.CharField(blank=True, help_text="Optional label, e.g. 'Tranche A', 'Director options', 'Critical-minerals super-FT'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='shareinstrument',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Strike price (warrants/options). Leave blank if unknown.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shareinstrument',
            name='type',
            field=models.CharField(choices=[('warrant', 'Warrant'), ('option', 'Option'), ('flow_through', 'Flow-through')], max_length=20),
        ),
    ]
