# Generated by Django 5.0.6 on 2026-05-14 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdict', '0018_alter_shareinstrument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHarvestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Never harvested'), ('harvesting', 'Harvest in progress'), ('ready', 'Ready for verdict'), ('blocked', 'Blocked — missing required data'), ('stale', 'Stale — re-harvest pending'), ('failed', 'Last harvest failed')], db_index=True, default='new', max_length=20)),
                ('last_harvest_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_successful_harvest', models.DateTimeField(blank=True, null=True)),
                ('last_published_scorecard', models.DateTimeField(blank=True, null=True)),
                ('next_retry_after', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('blockers_summary', models.TextField(blank=True, help_text='Auto-generated. Comma-separated unsatisfied REQUIRED items.')),
                ('ready_for_verdict', models.BooleanField(db_index=True, default=False, help_text='True iff every REQUIRED ChecklistItem is satisfied AND sanity-check passes.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_state', to='verdict.company')),
            ],
            options={
                'verbose_name': 'Company harvest state',
                'verbose_name_plural': 'Company harvest states',
                'ordering': ['company__ticker'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Stable identifier — e.g. 'mda_annual', 'shares_issued_outstanding'.", max_length=80)),
                ('category', models.CharField(choices=[('required', 'Required to publish scorecard'), ('recommended', 'Recommended — contributes to confidence'), ('optional', 'Optional — informational')], default='required', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('auto_filled', 'Auto-filled by harvester'), ('human_filled', 'Filled by human'), ('waived', 'Waived'), ('failed', 'Auto-fill failed')], db_index=True, default='pending', max_length=15)),
                ('source_type', models.CharField(blank=True, choices=[('sedar_harvester', 'SEDAR+ harvester'), ('human_upload', 'Human upload / paste'), ('external_api', 'External API / scraper'), ('agent_knowledge', 'Agent training-data knowledge'), ('derived', 'Derived from another item')], max_length=20)),
                ('source_ref', models.CharField(blank=True, help_text='sha256 of source PDF, URL, filename, or other provenance pointer.', max_length=200)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.JSONField(blank=True, help_text='The actual data — number, string, list, etc. Schema depends on key.', null=True)),
                ('waiver_reason', models.TextField(blank=True, help_text='Required when status=WAIVED. Audit trail.')),
                ('sanity_check_passed', models.BooleanField(default=False)),
                ('sanity_check_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Username or system identifier of whoever last touched this row.', max_length=60)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='verdict.company')),
            ],
            options={
                'verbose_name': 'Checklist item',
                'verbose_name_plural': 'Checklist items',
                'ordering': ['company__ticker', 'category', 'key'],
                'indexes': [models.Index(fields=['status', 'category'], name='verdict_che_status_0dad2b_idx'), models.Index(fields=['company', 'category'], name='verdict_che_company_d92023_idx')],
                'unique_together': {('company', 'key')},
            },
        ),
    ]
