# Generated by Django 5.0.6 on 2026-05-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdict', '0019_companyharveststate_checklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareinstrument',
            name='type',
            field=models.CharField(choices=[('warrant', 'Warrant'), ('option', 'Option'), ('flow_through', 'Flow-through'), ('rsu', 'Restricted/Performance share unit'), ('convertible', 'Convertible debenture/note')], max_length=20),
        ),
    ]
