# Generated by Django 5.0.6 on 2026-04-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verdict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_cache', to='verdict.company')),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('position', 'In Position'), ('sold', 'Sold / Exited'), ('dropped', 'Dropped from Watchlist')], db_index=True, default='watching', max_length=10)),
                ('thesis', models.TextField(help_text='Why this is on the watchlist.')),
                ('entry_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('position_size_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Portfolio allocation % (for accountability tracking).', max_digits=5, null=True)),
                ('next_catalyst', models.CharField(blank=True, help_text='e.g. Q3 drill results expected', max_length=200)),
                ('catalyst_date', models.DateField(blank=True, null=True)),
                ('public_notes', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_item', to='verdict.company')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
