# Generated by Django 6.0.4 on 2026-04-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text='Exact phrase to match (case-insensitive). E.g. "NI 43-101", "P/NAV multiple".', max_length=200, unique=True)),
                ('target_url', models.CharField(help_text='Relative path (e.g. /about/methodology/) or absolute URL.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['phrase'],
            },
        ),
        migrations.AlterModelOptions(
            name='commodityprice',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='commodityprice',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
