# Generated by Django 5.0.6 on 2026-04-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadMagnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='lead_magnets/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('homepage', 'Homepage'), ('blog', 'Blog Post'), ('video', 'Video Page'), ('verdict', 'Verdict / Scorecard'), ('watchlist', 'Watchlist'), ('lead_magnet', 'Lead Magnet'), ('api', 'API / Mobile App')], default='homepage', max_length=20)),
                ('mailchimp_synced', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lead_magnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='leads.leadmagnet')),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
