# Generated by Django 5.0.6 on 2026-04-10 21:10

import autoslug.fields
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Page title tag. 50–60 chars ideal. Leave blank to auto-derive.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description. 120–155 chars ideal. Leave blank to auto-derive.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing previews. 1200×630px recommended.', null=True, upload_to='og_images/%Y/%m/')),
                ('og_image_alt', models.CharField(blank=True, help_text='Alt text for the OG image — used by screen readers and some social platforms.', max_length=200)),
                ('title', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown in listings and used as fallback meta description.', max_length=500)),
                ('key_takeaways', models.JSONField(blank=True, default=list, help_text='List of short bullet strings. E.g. ["Score 19/25", "P/NAV 0.18x"]. Rendered at top of post and in schema.')),
                ('body', models.TextField(help_text='Supports Markdown or plain HTML.')),
                ('faq_items', models.JSONField(blank=True, default=list, help_text='List of {"question": "...", "answer": "..."} objects. Rendered as FAQ accordion + FAQPage JSON-LD.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/%Y/%m/')),
                ('featured_image_alt', models.CharField(blank=True, max_length=200)),
                ('pillar', models.CharField(choices=[('due-diligence', 'Due Diligence'), ('company-verdicts', 'Company Verdicts'), ('market-intelligence', 'Market Intelligence'), ('accountability', 'Accountability')], db_index=True, default='due-diligence', max_length=30)),
                ('is_premium', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Auto-calculated on save.')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx'), models.Index(fields=['pillar', 'status'], name='blog_post_pillar_87c2ca_idx')],
            },
        ),
    ]
