# Generated by Django 5.0.6 on 2026-04-11 17:27

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g. 'Due Diligence')", max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, help_text='SEO-focused description. Used in pillar landing page meta description.')),
                ('seo_title', models.CharField(blank=True, help_text='Custom meta title for pillar pages (50-60 chars ideal). Leave blank to auto-derive.', max_length=70)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order in nav, footer, and filters. Lower = first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive pillars are hidden from the site.')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_pillar__90012d_idx',
            old_name='blog_post_pillar_87c2ca_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='pillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.pillar'),
        ),
    ]
