# Generated by Django 5.0.6 on 2026-04-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_seed_pillars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillar',
            name='slug',
            field=models.SlugField(help_text='URL-safe identifier. Auto-generated from name if left blank. Edit to target specific SEO keywords.', max_length=100, unique=True),
        ),
    ]
