# Generated by Django 5.0.6 on 2026-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_pillar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer_capsule',
            field=models.TextField(blank=True, help_text='2-3 sentence direct answer to the post\'s core question. Displayed prominently before the body. AI platforms extract this for citations. E.g. "Based on our Verdict Framework, XYZ scores 19/25 and receives a BUY rating."'),
        ),
    ]
