# Generated by Django 5.0.6 on 2026-04-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_answer_capsule'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geo_target',
            field=models.CharField(blank=True, help_text='Optional geo target: "CA", "AU", "US", "UK". Used for hreflang tags.', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('standard', 'Standard Analysis'), ('listicle', 'Ranked List / Best-Of'), ('guide', 'Pillar Guide')], default='standard', help_text='Controls template layout. Listicle = ranked items. Guide = long-form with TOC.', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='ranked_items',
            field=models.JSONField(blank=True, default=list, help_text='For listicle posts. List of {"rank": 1, "name": "...", "ticker": "...", "summary": "...", "company_slug": "..."} objects. company_slug is optional.'),
        ),
    ]
