# Generated by Django 5.0.6 on 2026-04-10 21:10

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Page title tag. 50–60 chars ideal. Leave blank to auto-derive.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description. 120–155 chars ideal. Leave blank to auto-derive.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing previews. 1200×630px recommended.', null=True, upload_to='og_images/%Y/%m/')),
                ('og_image_alt', models.CharField(blank=True, help_text='Alt text for the OG image — used by screen readers and some social platforms.', max_length=200)),
                ('title', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('youtube_id', models.CharField(help_text='11-character YouTube video ID from the URL.', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('pillar', models.CharField(choices=[('due-diligence', 'Due Diligence'), ('company-verdicts', 'Company Verdicts'), ('market-intelligence', 'Market Intelligence'), ('accountability', 'Accountability')], db_index=True, default='due-diligence', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Leave blank to auto-derive from YouTube ID.')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
