# Generated by Django 5.0.6 on 2026-04-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditedInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('AU', 'Australia'), ('UK', 'United Kingdom'), ('US', 'United States'), ('OTHER', 'Other')], max_length=10)),
                ('capital_range', models.CharField(choices=[('50k-150k', '$50K – $150K'), ('150k-500k', '$150K – $500K'), ('500k-1m', '$500K – $1M'), ('1m+', '$1M+')], max_length=20)),
                ('referral_source', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('newsletter', 'Newsletter referral'), ('search', 'Search / Google'), ('social', 'Social media'), ('wom', 'Word of mouth'), ('other', 'Other')], max_length=20)),
                ('confirmed_accredited', models.BooleanField(default=False, help_text='Investor confirmed accredited status at time of registration.')),
                ('consent_contact', models.BooleanField(default=False, help_text='Investor consented to be contacted about deal flow.')),
                ('consent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, help_text='IP address at time of consent — retained for compliance.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('contacted', 'Contacted'), ('declined', 'Declined'), ('inactive', 'Inactive')], db_index=True, default='pending', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Private notes — not visible to investor.')),
                ('assigned_to', models.CharField(blank=True, help_text='Team member handling this lead.', max_length=100)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accredited Investor',
                'verbose_name_plural': 'Accredited Investors',
                'ordering': ['-registered_at'],
            },
        ),
    ]
